apiVersion: v1
kind: ServiceAccount
metadata:
  name: flask-app-sa
  namespace: flask-app
  annotations:
    azure.workload.identity/client-id: "YOUR_CLIENT_ID"
    azure.workload.identity/tenant-id: "YOUR_TENANT_ID"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flask-app-role
  namespace: flask-app
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flask-app-role-binding
  namespace: flask-app
subjects:
- kind: ServiceAccount
  name: flask-app-sa
  namespace: flask-app
roleRef:
  kind: Role
  name: flask-app-role
  apiGroup: rbac.authorization.k8s.io
